export { configureGit } from './configure-git.mjs'
export { configureNetlify } from './configure-netlify.mjs'
export { configureSanity } from './configure-sanity.mjs'
export { createProjectDir } from './create-project-dir.mjs'
export { getProjectInfo } from './get-project-info.mjs'
export { installDependencies } from './install-dependencies.mjs'
