const tableSeats = ['1-2', '3-4', '5-6', '7-8']

export default {
  TABLES: {
    TA: tableSeats,
    TB: tableSeats,
    TC: tableSeats,
    TD: tableSeats,
    TE: tableSeats,
    TF: tableSeats,
    TG: tableSeats,
    TH: tableSeats,
    TI: tableSeats,
    TJ: tableSeats,
    TK: tableSeats,
    TL: tableSeats,
    TM: tableSeats,
    TN: tableSeats,
    TO: tableSeats,
    TP: tableSeats,
  },
  STALLS: {
    A: 34,
    B: 34,
    C: 34,
    D: 34,
    E: 34,
    F: 34,
    G: 34,
    H: 34,
    I: 34,
    J: 34,
    K: 34,
    L: 34,
  },
  BALCONY: {
    M: 46,
    N: 42,
    O: 42,
    P: 38,
    Q: 32,
    R: 10,
  },
}
